baseURL = 'https://fatmanstouch.netlify.app//'
languageCode = 'en-us'
title = "Fat Man's Touch"
theme= "beautifulhugo"

[Params]
homeTitle = "Learning about Touch Rugby" # Set a different text for the header on the home page
subtitle = "Touchy Subjects ahead"

[Author]
website = "touch.hbgregorian.com"
email = "touch@hbgregorian.com"
github = ""